services:
  # FastAPI application - Staging
  api:
    image: ${DOCKER_USERNAME}/envoyou-sec-api:staging
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis
    volumes:
      - ./storage:/app/storage
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "journald"
  # Redis cache untuk Staging
  redis:
    image: redis:7-alpine
    restart: unless-stopped

# Tidak ada lagi volume untuk prometheus dan grafana
volumes: {}
